//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackendFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class content
    {
        public int id { get; set; }
        public string content_text { get; set; }
        public string content_author_name { get; set; }
        public string content_author_email { get; set; }
        public Nullable<int> user_id { get; set; }
        public string Content_sent_button { get; set; }
    
        public virtual User_Type User_Type { get; set; }
    }
}
