//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackendFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class exchange
    {
        public int id { get; set; }
        public string exchange_name { get; set; }
        public string exchange_buy { get; set; }
        public string exchange_sales { get; set; }
    }
}
