/*    ==Scripting Parameters==

    Source Server Version : SQL Server 2016 (13.0.4001)
    Source Database Engine Edition : Microsoft SQL Server Express Edition
    Source Database Engine Type : Standalone SQL Server

    Target Server Version : SQL Server 2016
    Target Database Engine Edition : Microsoft SQL Server Express Edition
    Target Database Engine Type : Standalone SQL Server
*/

USE [master]
GO

/****** Object:  Database [watcher]    Script Date: 12/23/2017 2:37:24 AM ******/
CREATE DATABASE [watcher]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'watcher', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\watcher.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'watcher_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\watcher_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [watcher] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [watcher].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [watcher] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [watcher] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [watcher] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [watcher] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [watcher] SET ARITHABORT OFF 
GO

ALTER DATABASE [watcher] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [watcher] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [watcher] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [watcher] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [watcher] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [watcher] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [watcher] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [watcher] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [watcher] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [watcher] SET  ENABLE_BROKER 
GO

ALTER DATABASE [watcher] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [watcher] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [watcher] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [watcher] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [watcher] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [watcher] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [watcher] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [watcher] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [watcher] SET  MULTI_USER 
GO

ALTER DATABASE [watcher] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [watcher] SET DB_CHAINING OFF 
GO

ALTER DATABASE [watcher] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [watcher] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [watcher] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [watcher] SET QUERY_STORE = OFF
GO

USE [watcher]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [watcher] SET  READ_WRITE 
GO

